import Nav from "./nav"
import Footer from "./footer"
import Head from 'next/head'


export default function  Layout({ children }) {
    return (
        <>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
      <main className="layout">

        {children}

        <Footer/>
        </main>
        </>
    )
}