import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
  <>
  
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      
      <main className="layout">
      <header className="thisheader">
          <h1>Simplicity Website</h1>
          <h2>A simple template for creating personal websites.</h2>
          </header>
        </main>
        
    
    </> 

  )
}
